japanizer: true
Discord:
  Token: ""
  ChatChannel:
  SystemChannel:
  LogChannel:
  NotificationChannel:

MySQL:
  Host: localhost
  User: root
  Password: ""
  Port: 3306
  SSL: true
  Database: man10_system