japanizer: true
Discord:
  Token: ""
  Guild:
  ChatChannel:
  SystemChannel:
  LogChannel:
  NotificationChannel:
  AdminChannel:

MySQL:
  Host: localhost
  User: root
  Password: ""
  Port: 3306
  SSL: true
  Database: man10_system